### ISSUE TITLE
Issue on windows

### ISSUE THREAD

**Issue by shyaml** [chbtoys/ppmpp#2]
I cannot compile the test 
 error   ppmpp.hpp:720:66: error: use of undeclared identifier 'M_PI'

does this work on windows with clang 16

**Comment by chbtoys** [comment]
Have you tried defining M_PI somewhere at the top of the code?

#define M_PI 3.14159265358979323846

The test has been compiled on Windows using msys2 and clang 16 without issues. The code was compiled with: clang++ -std=c++17 test.cpp -o test

**Comment by shyaml** [comment]
> Have you tried defining M_PI somewhere at the top of the code?
> 
> #define M_PI 3.14159265358979323846
> 
> The test has been compiled on Windows using msys2 and clang 16 without issues. The code was compiled with: clang++ -std=c++17 test.cpp -o test

well it works if M_PI  is defined in the  code

**Comment by shyaml** [comment]
clang++ -std=c++20  -pedantic -U_GNU_SOURCE test.cpp -o test   should do the trick
